name: rebuild and run ml pipeline

trigger:
- main

pool: 
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/mlops/python:latest

steps:
- script: |
   python3 src/pipeline.py
  displayName: 'Run Pipeline'