name: deploy ml model

trigger:
- main

pool: 
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/mlops/python:latest

steps:
- script: |
    pip3 install azureml-sdk
    python3 src/deploy.py
  displayName: 'Run Pipeline'